spring:
  application:
    name: spring-admin
  cloud:
    config:
      enabled: false
server:
  port: 8762
info:
  app:
    name: ${spring.application.name}
eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-registry-service/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info



