spring:
  application:
    name: spring-admin
  cloud:
    config:
      enabled: false
info:
  app:
    name: ${spring.application.name}
server:
  port: 8762
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info



