apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-admin
  labels:
    app: spring-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-admin
  template:
    metadata:
      labels:
        app: spring-admin
    spec:
      containers:
        - name: spring-admin
          image: bartoszbud/spring-admin:DEV-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8762